name: "🏷️ Tag version"
description: "Checkout code, setup Node.js, and tag version."

inputs:
  node-version:
    description: "Version de Node.js"
    required: false
    default: "21"
  path:
    description: "Chemin vers le dossier contenant le fichier package.json"
    required: false
    default: "."

outputs:
  VERSION:
    description: "Version du package"

runs:
  using: "composite"
  steps:
    - name: 📦 Setup
      uses: kilianpichard/actions/setup@main
      with:
        path: api

    - name: 🚀 Release with semantic-release
      run: |
        cd api
        npx semantic-release

    - name: 🏷️ Get version
      id: get_version
      run: |
        if [ ! -f api/version.txt ]; then
          LATEST_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo $LATEST_VERSION | sed 's/v//' > api/version.txt
        fi
        VERSION=$(cat api/version.txt)
        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
