name: "🧹 Lint code"
description: "Checkout code, setup Node.js, and lint code."
inputs:
  node-version:
    description: "Version de Node.js"
    required: false
    default: "21"
  path:
    description: "Chemin vers le dossier contenant le fichier package.json"
    required: false
    default: "."
outputs: {}
runs:
  using: "composite"
  steps:
    - name: 📦 Setup
      uses: kilianpichard/actions/setup@main
      with:
        node-version: ${{ inputs.node-version }}
        path: ${{ inputs.path }}
    - name: 🧹 Lint code
      shell: bash
      run: |
        cd ${{ inputs.path }}
