name: CI/CD 🚀

on:
  workflow_call:
    inputs:
      path:
        description: "Path to the application"
        required: true
        default: "app"
        type: string
      runBuildCommand:
        description: "Command to build the application"
        required: false
        default: ""
        type: string
      preBuildCommand:
        description: "Command to run before building the application"
        required: false
        default: ""
        type: string
      app_name:
        description: "Name of the application"
        required: true
        type: string
      app_folder:
        description: "Folder of the application"
        required: true
        type: string
      stack_name:
        description: "Name of the stack"
        required: true
        type: string

env:
  EC2_SSH: ${{ secrets.EC2_SSH }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  install:
    name: 📥 Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Install Dependencies
        uses: kilianpichard/actions/install@main
        with:
          path: ${{ inputs.path }}

  lint:
    name: 🧹 Lint Code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: 🧹 Lint Code
        uses: kilianpichard/actions/lint@main
        with:
          path: ${{ inputs.path }}

  release:
    name: 🏷️ Tag Version
    needs: install
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag_version.outputs.VERSION }}
    steps:
      - name: 🏷️ Tag Version
        id: tag_version
        uses: kilianpichard/actions/tag_version@main
        with:
          path: ${{ inputs.path }}

  build:
    name: 🛠️ Build and Push Docker Image
    needs: [release, lint]
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64
      VERSION: ${{ needs.release.outputs.version }}
    steps:
      - name: Setup
        uses: kilianpichard/actions/setup@main
        with:
          path: ${{ inputs.path }}
      - name: Pre Build
        if: ${{ inputs.preBuildCommand != '' }}
        run: ${{ inputs.preBuildCommand }}
      - name: 🛠️ Build and Push Docker Image
        uses: kilianpichard/actions/build@main
        with:
          path: ${{ inputs.path }}
          version: ${{ env.VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          runBuildCommand: ${{ inputs.runBuildCommand }}

  deploy:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    needs: [release, build]
    env:
      VERSION: ${{ needs.release.outputs.version }}
    steps:
      - name: 🚀 Deploy to Production
        uses: kilianpichard/actions/deploy@main
        with:
          version: ${{ env.VERSION }}
          ec2_ssh: ${{ secrets.EC2_SSH }}
          ec2_user: ${{ secrets.EC2_USER }}
          ec2_host: ${{ secrets.EC2_HOST }}
          app_name: ${{ github.ref == 'refs/heads/main' && '${{ inputs.app_name }}' || '${{ inputs.app_name }}_STAGING' }}
          app_folder: ${{ inputs.app_folder }}
          stack_name: ${{ inputs.stack_name }}
